### ISSUE TITLE
Current example of running the server?

### ISSUE THREAD

**Issue by mikoskinen** [vforteli/Flexinets.Radius.RadiusServer#11]
Thanks for the interesting project.

I wonder if there's a current example of running a server available? The example in readme.md doesn't seem to work anymore as the code library has changed.

**Comment by vforteli** [comment]
I guess I have neglected the readme for a while. I updated the sample in the readme to reflect the newer version.
Still needs some clean up though

**Comment by mikoskinen** [comment]
Great, thank you for the quick help :)
